# Generated by Django 4.2.13 on 2024-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salaries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
