# Generated by Django 4.2.13 on 2024-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salaries", "0002_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="education_level",
            field=models.CharField(default="null", max_length=30),
        ),
    ]
